### ISSUE TITLE
Ensure registry and router are deployed

### ISSUE THREAD

**Issue by navidshaikh** [CentOS/container-pipeline-service#318]
Check https://github.com/CentOS/container-pipeline-service/blob/master/provisions/roles/openshift/tasks/setup.yml#L2-L21

```
- name: Setup openshift registry
  command: "{{item}}"
  with_items:
    - oadm registry -n default --config={{ openshift_dir }}/admin.kubeconfig
    - oadm policy add-scc-to-group anyuid system:authenticated
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  ignore_errors: yes

- name: Wait for Openshift Registry to come up
  pause: seconds={{ openshift_startup_delay }}

- name: Setup openshift router
  shell: "{{ item }}"
  with_items:
    - oc get scc privileged -o json | sed '/\"users\"/a \"system:serviceaccount:default:router\",' | oc replace scc privileged -f -
    - oadm router --create --credentials={{ openshift_dir }}/openshift-router.kubeconfig --service-account=router
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  ignore_errors: yes
```

if check the option `ignore_errors: yes` , which means, if there is any issue in deploying registry or router, the provisioning scripts are going to be failed. Which means, we are not sure after deployment if the registry and router are deployed, one needs to check it manually.
This hit us once.
We need to change that and ensure that router and registry are up.
