### ISSUE TITLE
Remove references of personnel namespaced repositories

### ISSUE THREAD

**Issue by navidshaikh** [CentOS/container-pipeline-service#437]
Following from https://github.com/CentOS/container-pipeline-service/blob/master/provisions/roles/repo_tracking/tasks/main.yml#L91-L96 needs to be removed/replaced.

```
- name: Get container index
  git:
    repo: https://github.com/rtnpro/container-index
    dest: /opt/container-index
  sudo: yes
  tags: repo_tracking
```

@dharmit : PTAL, do we need to manage a replacement here? I don't see any reference to the target location of container-index in the code, can you please confirm ?
